language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_script:
  - npm install -g bower polymer-cli
  - bower install
cache: yarn
script:
  - xvfb-run npm test -l chrome
